### PR TITLE
reporting buttons fixes

### LINKED ISSUE #2570: Bug - button display and functionality
checklist:

- [x] 1
- [x] 2
- [x] 3
- [x] 4
- [x] 5

#### Describe the Bug:

1. `Continue` button displays
   - ` Person responsible` when person responsible is empty

2. `Cancel` button displays
   -  `Attachments`

3. `Back` button is missing
   - `Attachments`
   - `Allocation of Emission`

4. `Save` button is missing
   - `Attachments`

5. `Save` and `Save and Continue` perform same routing function
   - `Production Data`
   - `Allocation of Emission`

#### Steps to reproduce the behaviour:

1. `Continue` button displays
   - ` Person responsible` when person responsible is empty
http://localhost:3000/reporting/reporting/reports/3/person-responsible
Image

2. `Cancel` button displays
   -  `Attachments`
http://localhost:3000/reporting/reports/3/attachments
Image

3. `Back` button is missing
   - `Attachments`
http://localhost:3000/reporting/reports/3/attachments
Image
   - `Allocation of Emission`
 http://localhost:3000/reporting/reports/3/facilities/f486f2fb-62ed-438d-bb3e-0819b51e3aff/allocation-of-emissions
Image

4. `Save` button is missing
   - `Attachments`
http://localhost:3000/reporting/reports/3/attachments
Image

5. `Save` and `Save and Continue` perform routing same function
   - `Production Data`
 http://localhost:3000/reporting/reports/3/facilities/f486f2fb-62ed-438d-bb3e-0819b51e3aff/production-data
   - `Allocation of Emission`
http://localhost:3000/reporting/reports/3/facilities/f486f2fb-62ed-438d-bb3e-0819b51e3aff/allocation-of-emissions

#### Additional information:

Browser: [e.g. chrome, safari]
Version: [e.g. 22]

#### Additional Context

-

### PR DESCRIPTION
**Pull request by gdalcengio**
#2570

- fix: Fix reporting step buttons on attachments and allocation pages
- test: update tests after reporting step buttons update

### 🔬 SH Post Review - Testing:

1. From terminal command, start the api server:
 ```
cd bc_obps
make reset_db
make run
```  
2.  From terminal command, start the app development server:
 ```
cd bciers && yarn dev-all
```  

1. Navigate to http://localhost:3000
2. Click button "Log in with Business BCeID"
3. Navigate to http://localhost:3000/reporting/reports
**Expected Results**
- Reporting grid displays with rows having action buttons `Start` or  `Continue`
5. Click `Operator 3` row button `Start`
**Expected Results**
- Url does NOT display any query parameters  such as`..?reports_title=...1
- Router navigates to form: `Review operation information` 
- Form has buttons: `Back`; `Save`; `Save & Continue`
6. Navigate to http://localhost:3000/reporting/reports
7.  Click `Operator 3` row button `Continue`
**Expected Results**
- Url does NOT display any query parameters  such as`..?reports_title=...1
- Router navigates to form: `Review operation information` 
- Form has buttons: `Back`; `Save`; `Save & Continue`
8. Click button `Back`
**Expected Results**
- Router navigates to the previous next step
9.  Click `Operator 3` row button `Continue`
10. Click button  `Save`
**Expected Results**
- Form POST data to the server
- Router does not navigate to the next step
11. Click button `Save & Continue`
**Expected Results**
- Form POST data to the server
- Router navigates to form: `Person Responsible`
- Form has buttons: `Back`; `Save`; `Save & Continue`
12. Click button `Back`
**Expected Results**
- Router navigates to the previous next step
13. Click button `Save & Continue`
- Form POST data to the server
- Router navigates to form: `Person Responsible`
14. Complete form and click button `Save`
**Expected Results**
- Form POST data to the server
- Router does not navigate to the next step
15. Click button `Save & Continue`
**Expected Results**
- Form POST data to the server
- Router navigates to form: `Review facility information`
- Form has buttons: `Back`; `Save`; `Save & Continue`
16. Click button `Back`
**Expected Results**
- Router navigates to the previous next step
17. Click button `Save & Continue`
- Form POST data to the server
- Router navigates to form: `Review facility information`
18. Complete form and click button `Save`
**Expected Results**
- Form POST data to the server
- Router does not navigate to the next step
19. Click button `Save & Continue`
**Expected Results**
- Form POST data to the server
- Router navigates to form: `General stationary combustion excluding line tracing`
- Form has buttons: `Back`; `Save`; `Save & Continue`
20. Click button `Back`
**Expected Results**
- Router navigates to the previous next step
21. Click button `Save & Continue`
- Form POST data to the server
- Router navigates to form: `General stationary combustion excluding line tracing`
22. Complete form and click button `Save`
**Expected Results**
- Form POST data to the server
- Router does not navigate to the next step
23. Click button `Save & Continue`
**Expected Results**
- Form POST data to the server
- Router navigates to form: `Activities` (currently "Something went wrong...")
24. Navigate to http://localhost:3000/reporting/reports/3/facilities/f486f2fb-62ed-438d-bb3e-0819b51e3aff/non-attributable
- Router navigates to form: `Non-Attributable Emissions`
- Form has buttons: `Back`; `Save`; `Save & Continue`
25. Complete form and click button `Save`
**Expected Results**
- Form POST data to the server
- Router does not navigate to the next step
26. Click button `Save & Continue`
**Expected Results**
- Form POST data to the server
- Router navigates to form: `Emission Summary`
- Form has buttons: `Back`; `Save`; `Continue`
- Button `Save` is disabled
27. Click button `Continue`
**Expected Results**
- Router navigates to form: `Production Data`
- Form has buttons: `Back`; `Save`; `Save & Continue`
29. Click button `Back`
**Expected Results**
- Router navigates to the 'Emission Summary`
30. Click button `Continue`
**Expected Results**
- Router navigates to form: `Production Data`
31. Complete form and click button `Save`
**Expected Results**
- Form POST data to the server
- Router does not navigate to the next step
32. Click button `Save & Continue`
**Expected Results**
- Form POST data to the server
- Router navigates to form; `Allocation Of Emissions`
- Form has buttons: `Back`; `Save`; `Save & Continue`
33. Click button `Back`
**Expected Results**
- Router navigates to the previous next step
34. Click button `Save & Continue`
- Form POST data to the server
- Router navigates to form: `Allocation Of Emissions`
35. Complete form and click button `Save`
**Expected Results**
- Form POST data to the server
- Router does not navigate to the next step
36. Click button `Save & Continue`
**Expected Results**
- Form POST data to the server
- Router navigates to form: `Additional Reporting Data`
- Form has buttons: `Back`; `Save`; `Save & Continue`
37. Click button `Back`
**Expected Results**
- Router navigates to the previous next step
38. Click button `Save & Continue`
- Form POST data to the server
- Router navigates to form: `Additional Reporting Data`
39. Complete form and click button `Save`
**Expected Results**
- Form POST data to the server
- Router does not navigate to the next step
40. Click button `Save & Continue`
**Expected Results**
- Form POST data to the server
- Router navigates to form: `new-entrant-information` (coming soon)
- Form has buttons: `Back`; `Save`; `Save & Continue`
 41. Navigate to http://localhost:3000/reporting/reports/3/verification
**Expected Results**
- Router navigates to form: `Verification`
- Form has buttons: `Back`; `Save`; `Save & Continue`
42. Complete form and click button `Save`
**Expected Results**
- Form POST data to the server
- Router does not navigate to the next step
43. Click button `Save & Continue`
**Expected Results**
- Form POST data to the server
- Router navigates to form; `Attachments`
- Form has buttons: `Back`; `Save`; `Save & Continue`
44. Click button `Back`
**Expected Results**
- Router navigates to the previous next step
45. Click button `Save & Continue`
- Form POST data to the server
- Router navigates to form: `Attachments`
46. Complete form and click button `Save`
**Expected Results**
- Form POST data to the server
- Router does not navigate to the next step
47. Click button `Save & Continue`
**Expected Results**
- Form POST data to the server
- Router navigates to form; `Final Review`
- Form has buttons: `Back`; `Save`; `Save & Continue`
48. Click button `Back`
**Expected Results**
- Router navigates to the previous next step
49. Click button `Save & Continue`
- Form POST data to the server
- Router navigates to form: `Final Review`
50. Complete form and click button `Save`
**Expected Results**
- Router does not navigate to the next step
51. Click button `Save & Continue`
**Expected Results**
- Router navigates to form; `Sign Off`
- Form has buttons: `Back`; `Save`; `Save & Continue`
- Button `Save` is disabled
52. Click button `Back`
**Expected Results**
- Router navigates to the previous next step
53. Click button `Save & Continue`
- Router navigates to form; `Sign Off`
54. Complete form and click button `Save & Continue`
**Expected Results**
- `Successful Submission` displays

### CODE REVIEW

File: bciers/apps/reporting/src/app/components/signOff/SignOffPage.tsx [hunk 1]
```diff
@@ -29,11 +30,13 @@ const taskListElements: TaskListElement[] = [
   },
 ];
 
-export default function SignOffPage() {
+const SignOffPage: React.FC<HasReportVersion> = ({ version_id }) => {
```
Comment (shon-button) [inline bciers/apps/reporting/src/app/components/signOff/SignOffPage.tsx:33]: @gdalcengio  
For your consideration:
IMO, for Next.js apps, if your component is a page component, the preferred pattern is a function declarations with export default- `export default function SignOffPage({ version_id }: HasReportVersion) {...`  
This pattern aligns with the framework's dynamic routing and file-based conventions, and since we don't typically need to handle children for page components React.FC adds little value.

**Comment by shon-button** [comment]
@gdalcengio 

For me, this is still an issue:
- Save and Save and Continue perform same routing function
http://localhost:3000/reporting/reports/3/facilities/f486f2fb-62ed-438d-bb3e-0819b51e3aff/production-data

**Comment by shon-button** [comment]
@gdalcengio 

nit: some navigation include obsolete query parameters no longer needed by report breadcrumbs

**Comment by shon-button** [comment]
@gdalcengio 
FYI: `Additional Reporting Data` does not have a `Back` button

File: bciers/apps/reporting/src/app/components/operations/personResponsible/PersonResponsible.tsx [hunk 2]
```diff
@@ -42,12 +40,11 @@ const PersonResponsible = ({ version_id }: Props) => {
 
   const [schema, setSchema] = useState<RJSFSchema>(personResponsibleSchema);
 
-  const queryString = serializeSearchParams(useSearchParams());
   const continueUrl =
     operationType === "Linear Facility Operation"
-      ? `/reporting/reports/${version_id}/facilities/lfo-facilities${queryString}`
```
Comment (shon-button) [inline bciers/apps/reporting/src/app/components/operations/personResponsible/PersonResponsible.tsx:48]: FYI: incorrect `/reporting/reports/` instead of `/reports/`

File: bciers/apps/reporting/src/app/components/additionalInformation/additionalReportingData/AdditionalReportingDataForm.tsx [hunk 3]
```diff
@@ -44,9 +41,17 @@ export default function AdditionalReportingDataForm({
...
+  const facilityId = searchParams.get("facility_id");
+  const backUrl = `/reports/${versionId}/facilities/${facilityId}/allocation-of-emissions`;
+
   const saveAndContinueUrl = `/reports/${versionId}/new-entrant-information`;
+  /** // 🛸 Set up routing urls
+  const searchParams = useSearchParams();
+  const facilityId = searchParams.get("facility_id");
+  const backUrl = `/reports/${versionId}/facilities/${facilityId}/allocation-of-emissions`;
 
+ */
```
Comment (acatchpole) [inline bciers/apps/reporting/src/app/components/additionalInformation/additionalReportingData/AdditionalReportingDataForm.tsx:54]: commented code still present

**Review by acatchpole — APPROVED** [review]
local testing confirms working. Only possible issue noticed is :
On 'Review Operation Information' page: clicking "Save" generates error = 
    An error occurred while fetching /reporting/report-version/3/report-operation: SyntaxError: Unexpected token '<', "
    <!doctype "... is not valid JSON
    - status 200 is still returned from the POST and seem to function properly. Behaviour is NOT seen when clicking "Save and Continue". probably not an issue that would be noticed in testing tomorrow

**Comment by shon-button** [comment]
> local testing confirms working. Only possible issue noticed is : On 'Review Operation Information' page: clicking "Save" generates error = An error occurred while fetching /reporting/report-version/3/report-operation: SyntaxError: Unexpected token '<', " <!doctype "... is not valid JSON - status 200 is still returned from the POST and seem to function properly. Behaviour is NOT seen when clicking "Save and Continue". probably not an issue that would be noticed in testing tomorrow

Thanks @acatchpole !

I also noticed that (On 'Review Operation Information' page: clicking "Save"  without any data) generates error.  I have a note to create a possible ticket!

**Comment by shon-button** [comment]
Capturing `Additional Reporting Data` buttons display in this branch:
image

**Comment by gdalcengio** [comment]
Thank you @shon-button. I really appreciate you cleaning up all the mess I left!
